name: Validate
on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/docker-builder
      - name: Run a thing
        run: |
          node -v
          yarn build
